# TO_BE_UPDATED

title: Premkumar Masilamani
tagline: On a journey called Life
url: https://www.premkumarmasilamani.com
#logo: add-some-logo-here
copyright: copyleft @ 2009.

author: Premkumar Masilamani
email: premkumar.masilamani.2020@gmail.com
mobile: xxx-xxx-xxxx

social:
  name: Premkumar Masilamani
  links:
    - https://www.linkedin.com/in/premkumarmasilamani
    - https://github.com/premkumar-masilamani

include:
  - "_pages"

plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

paginate: 1000

permalink: /:title/

img-path: https://www.premkumarmasilamani.com/public/images
download-path: https://www.premkumarmasilamani.com/public/downloads

newsletter: https://eepurl.com/dE1QD1

home-page-url: https://www.premkumarmasilamani.com
software-architect-url: https://www.linkedin.com/in/premkumarmasilamani
english-blog-url: https://www.premkumarmasilamani.com/blog
tamil-blog-url: https://tamil.smileprem.com/
life-coach-url: https://cal.com/coachprem/chemistry-session