home: https://www.premkumarmasilamani.com
copyright: copyleft @ 2009.

linkedin: https://www.linkedin.com/in/premkumar-masilamani/
github: https://github.com/premkumar-masilamani
coach: https://www.premkumarmasilamani.com/coach.html

english:
  blog:
    title: The Unquiet Mind
    author: Premkumar Masilamani
    email: premkumar.masilamani.2020@gmail.com
    url: https://www.premkumarmasilamani.com/english/blog
    downloads: https://www.premkumarmasilamani.com/downloads/english/blog
    subscription_text: "Thanks for reading my blog post! I hope it made you think. Stay updated with the latest posts via:"
    breadcrumbs_texts:
      home: home
      item: blogs
  podcast:
    title: The Beautiful Contradiction
    author: Premkumar Masilamani
    email: premkumar.masilamani.2020@gmail.com
    url: https://www.premkumarmasilamani.com/english/podcast
    downloads: https://www.premkumarmasilamani.com/downloads/english/podcast
    subscription_text: "Thanks for listening to my podcast! I hope it made you think. Stay updated with the latest episodes via:"
    breadcrumbs_texts:
      home: home
      item: episodes
tamil:
  blog:
    title: பேரன்பும் பெருங்கோபமும்
    author: பிரேம்குமார் மாசிலாமணி
    email: premkumar.masilamani.2020@gmail.com
    url: https://www.premkumarmasilamani.com/tamil/blog
    downloads: https://www.premkumarmasilamani.com/downloads/tamil/blog
    subscription_text: "இந்த வலைப்பதிவை படித்ததற்கு நன்றி. இது உங்களை மகிழ்வித்து இருக்கும் அல்லது சிந்திக்க தூண்டியிருக்குமென நம்புகிறேன். தொடர்ந்து என்னுடைய பதிவுகளை பெற:"
    breadcrumbs_texts:
      home: முகப்பு
      item: வலைப்பதிவுகள்
  podcast:
    title: நிகழே அதுவே
    author: பிரேம்குமார் மாசிலாமணி
    email: premkumar.masilamani.2020@gmail.com
    description: இந்த நிமிஷம் என்ன தோணுதோ, அதையே பேசறேன் - நிகழே அதுவே
    url: https://www.premkumarmasilamani.com/tamil/podcast
    downloads: https://www.premkumarmasilamani.com/downloads/tamil/podcast
    gcs_bucket: https://storage.googleapis.com/premkumar-masilamani-podcast-nigazhe-adhuve
    subscription_text: "Thanks for listening to my podcast! I hope it made you think. Stay updated with the latest episodes via:"
    breadcrumbs_texts:
      home: முகப்பு
      item: அத்தியாயங்கள்

include:
  - "_pages"

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

paginate: 1000
