title: Premkumar Masilamani
tagline: On a journey called Life
home: https://www.premkumarmasilamani.com
copyright: copyleft @ 2009.

linkedin: https://www.linkedin.com/in/premkumar-masilamani/
github: https://github.com/premkumar-masilamani
coach: https://www.premkumarmasilamani.com/coach.html
email: premkumar.masilamani.2020@gmail.com

english:
  blog:
    title: Premkumar Masilamani
    tagline: On a journey called Life
    author: Premkumar Masilamani
    url: https://www.premkumarmasilamani.com/english/blog
    downloads: https://www.premkumarmasilamani.com/downloads/english/blog
    newsletter: https://eepurl.com/dE1QD1
  podcast:
    title: Podcast Title
    tagline: Podcast Tagline
    author: Premkumar Masilamani
    url: https://www.premkumarmasilamani.com/english/podcast
    downloads: https://www.premkumarmasilamani.com/downloads/english/podcast
    newsletter: https://eepurl.com/dE1QD1

tamil:
  blog:
    title: பிரேம்குமார் மாசிலாமணி
    tagline: என் வாழ்வென்னும் பயணத்தில்...
    author: பிரேம்குமார் மாசிலாமணி
    url: https://www.premkumarmasilamani.com/tamil
    downloads: https://www.premkumarmasilamani.com/downloads/tamil/blog
    newsletter: https://eepurl.com/dE1xBb
  podcast:
    title: Podcast Title
    tagline: Podcast Tagline
    author: பிரேம்குமார் மாசிலாமணி
    url: https://www.premkumarmasilamani.com/tamil/podcast
    downloads: https://www.premkumarmasilamani.com/downloads/tamil/podcast
    newsletter: https://eepurl.com/dE1xBb

include:
  - "_pages"

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

paginate: 1000

permalink: /:categories/:title/
