title: Premkumar Masilamani
tagline: On a journey called Life
url: https://www.premkumarmasilamani.com
copyright: copyleft @ 2009.

english:
  title: Premkumar Masilamani
  tagline: On a journey called Life
  author: Premkumar Masilamani
  url: https://www.premkumarmasilamani.com/english
  img-path: https://www.premkumarmasilamani.com/downloads/images
  download-path: https://www.premkumarmasilamani.com/downloads/files
  newsletter: https://eepurl.com/dE1QD1
  email: premkumar.masilamani.2020@gmail.com

tamil:
  title: பிரேம்குமார் மாசிலாமணி
  tagline: என் வாழ்வென்னும் பயணத்தில்...
  author: பிரேம்குமார் மாசிலாமணி
  url: https://www.premkumarmasilamani.com/tamil
  img-path: https://www.premkumarmasilamani.com/downloads/images
  download-path: https://www.premkumarmasilamani.com/downloads/files
  newsletter: https://eepurl.com/dE1xBb
  email: premkumar.masilamani.2020@gmail.com

urls:
  linkedin: https://www.linkedin.com/in/premkumar-masilamani/
  github: https://github.com/premkumar-masilamani
  coach: https://topmate.io/premkumar_masilamani

include:
  - "_pages"

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

paginate: 1000

permalink: /:categories/:title/
