title: Premkumar Masilamani
tagline: On a journey called Life
home: http://localhost:4000
copyright: copyleft @ 2009.

linkedin: https://www.linkedin.com/in/premkumar-masilamani/
github: https://github.com/premkumar-masilamani
coach: http://localhost:4000/coach.html
email: premkumar.masilamani.2020@gmail.com

english:
  blog:
    title: Premkumar Masilamani
    tagline: On a journey called Life
    author: Premkumar Masilamani
    url: http://localhost:4000/english/blog
    downloads: http://localhost:4000/downloads/english/blog
    newsletter: https://eepurl.com/dE1QD1
    subscription_text: "Thanks for reading my blog post! I hope it made you think. Stay updated with the latest posts via:"
    breadcrumbs_texts:
      home: home
      item: blogs
  podcast:
    title: Podcast Title
    tagline: Podcast Tagline
    author: Premkumar Masilamani
    url: http://localhost:4000/english/podcast
    downloads: http://localhost:4000/downloads/english/podcast
    newsletter: https://eepurl.com/dE1QD1
    subscription_text: "Thanks for listening to my podcast! I hope it made you think. Stay updated with the latest episodes via:"
    breadcrumbs_texts:
      home: home
      item: episodes
tamil:
  blog:
    title: பிரேம்குமார் மாசிலாமணி
    tagline: என் வாழ்வென்னும் பயணத்தில்...
    author: பிரேம்குமார் மாசிலாமணி
    url: http://localhost:4000/tamil/blog
    downloads: http://localhost:4000/downloads/tamil/blog
    newsletter: https://eepurl.com/dE1xBb
    subscription_text: "இந்த வலைப்பதிவை படித்ததற்கு நன்றி. இது உங்களை மகிழ்வித்து இருக்கும் அல்லது சிந்திக்க தூண்டியிருக்குமென நம்புகிறேன். தொடர்ந்து என்னுடைய பதிவுகளை பெற:"
    breadcrumbs_texts:
      home: முகப்பு
      item: வலைப்பதிவுகள்
  podcast:
    title: Podcast Title
    tagline: Podcast Tagline
    author: பிரேம்குமார் மாசிலாமணி
    url: http://localhost:4000/tamil/podcast
    downloads: http://localhost:4000/downloads/tamil/podcast
    newsletter: https://eepurl.com/dE1xBb
    subscription_text: "Thanks for listening to my podcast! I hope it made you think. Stay updated with the latest episodes via:"
    breadcrumbs_texts:
      home: முகப்பு
      item: அத்தியாயங்கள்

include:
  - "_pages"

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

paginate: 1000

# Enable this setting when running the docker from India.
timezone: Asia/Kolkata
