home: http://localhost:4000
copyright: copyleft @ 2009.

linkedin: https://www.linkedin.com/in/premkumar-masilamani
github: https://github.com/premkumar-masilamani

breadcrumbs_texts:
  home:
    english: "home"
    tamil: "முகப்பு"
  lang:
    english: "english"
    tamil: "தமிழ்"
  channels:
    english:
      blog: "blog"
      podcast: "podcast"
    tamil:
      blog: "வலைப்பதிவு"
      a400: "அகநானூறு"
      podcast: "வளையொலி"

english:
  blog:
    title: The Unquiet Mind
    author: Premkumar Masilamani
    email: premkumar.masilamani.2020@gmail.com
    url: http://localhost:4000/english/blog
    downloads: http://localhost:4000/downloads/english/blog
  podcast:
    title: The Beautiful Contradiction
    author: Premkumar Masilamani
    email: premkumar.masilamani.2020@gmail.com
    url: http://localhost:4000/english/podcast
    downloads: http://localhost:4000/downloads/english/podcast
tamil:
  blog:
    title: பேரன்பும் பெருங்கோபமும்
    author: பிரேம்குமார் மாசிலாமணி
    email: premkumar.masilamani.2020@gmail.com
    url: http://localhost:4000/tamil/blog
    downloads: http://localhost:4000/downloads/tamil/blog
  a400:
    title: அகநானூறு
    author: பிரேம்குமார் மாசிலாமணி
    email: premkumar.masilamani.2020@gmail.com
    url: http://localhost:4000/tamil/a400
    downloads: http://localhost:4000/downloads/tamil/a400
  podcast:
    title: நிகழே அதுவே
    description: இந்த நிமிஷம் என்ன தோணுதோ, அதையே பேசறேன் - நிகழே அதுவே
    author: பிரேம்குமார் மாசிலாமணி
    email: premkumar.masilamani.2020@gmail.com
    url: http://localhost:4000/tamil/podcast
    downloads: http://localhost:4000/downloads/tamil/podcast
    gcs_bucket: https://storage.googleapis.com/premkumar-masilamani-podcast-nigazhe-adhuve

include:
  - "_pages"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Enable this setting when running the docker from India.
timezone: Asia/Kolkata
