home: http://localhost:4000
copyright: copyleft @ 2009.

linkedin: https://www.linkedin.com/in/premkumar-masilamani
github: https://github.com/premkumar-masilamani

english:
  blog:
    title: The Unquiet Mind
    author: Premkumar Masilamani
    email: premkumar.masilamani.2020@gmail.com
    url: http://localhost:4000/english/blog
    downloads: http://localhost:4000/downloads/english/blog
    breadcrumbs_texts:
      home: home
      item: blog
  podcast:
    title: The Beautiful Contradiction
    author: Premkumar Masilamani
    email: premkumar.masilamani.2020@gmail.com
    url: http://localhost:4000/english/podcast
    downloads: http://localhost:4000/downloads/english/podcast
    breadcrumbs_texts:
      home: home
      item: podcast
tamil:
  blog:
    title: பேரன்பும் பெருங்கோபமும்
    author: பிரேம்குமார் மாசிலாமணி
    email: premkumar.masilamani.2020@gmail.com
    url: http://localhost:4000/tamil/blog
    downloads: http://localhost:4000/downloads/tamil/blog
    breadcrumbs_texts:
      home: முகப்பு
      item: வலைப்பதிவு
  a400:
    title: அகநானூறு
    author: பிரேம்குமார் மாசிலாமணி
    email: premkumar.masilamani.2020@gmail.com
    url: http://localhost:4000/tamil/a400
    downloads: http://localhost:4000/downloads/tamil/a400
    breadcrumbs_texts:
      home: முகப்பு
      item: அகநானூறு
  podcast:
    title: நிகழே அதுவே
    description: இந்த நிமிஷம் என்ன தோணுதோ, அதையே பேசறேன் - நிகழே அதுவே
    author: பிரேம்குமார் மாசிலாமணி
    email: premkumar.masilamani.2020@gmail.com
    url: http://localhost:4000/tamil/podcast
    downloads: http://localhost:4000/downloads/tamil/podcast
    gcs_bucket: https://storage.googleapis.com/premkumar-masilamani-podcast-nigazhe-adhuve
    breadcrumbs_texts:
      home: முகப்பு
      item: வளையொலி

include:
  - "_pages"

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

paginate: 1000

# Enable this setting when running the docker from India.
timezone: Asia/Kolkata
