title: Premkumar Masilamani
tagline: On a journey called Life
url: http://localhost:4000
copyright: copyleft @ 2009.

english:
  title: Premkumar Masilamani
  tagline: On a journey called Life
  author: Premkumar Masilamani
  url: http://localhost:4000/english
  img-path: http://localhost:4000/english/public/images
  download-path: http://localhost:4000/english/public/downloads
  newsletter: https://eepurl.com/dE1QD1
  email: premkumar.masilamani.2020@gmail.com

tamil:
  title: பிரேம்குமார் மாசிலாமணி
  tagline: என் வாழ்வென்னும் பயணத்தில்...
  author: பிரேம்குமார் மாசிலாமணி
  url: http://localhost:4000/tamil
  img-path: http://localhost:4000/tamil/public/images
  download-path: http://localhost:4000/tamil/public/downloads
  newsletter: https://eepurl.com/dE1xBb
  email: premkumar.masilamani.2020@gmail.com

urls:
  linkedin: https://www.linkedin.com/in/premkumar-masilamani/
  github: https://github.com/premkumar-masilamani
  coach: https://topmate.io/premkumar_masilamani

include:
  - "_pages"

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

paginate: 1000

permalink: /:categories/:title/

# Enable this setting when running the docker from India.
timezone: Asia/Kolkata
